[package]
authors = ["Andy Balaam <andy.balaam@matrix.org>"]
edition = "2021"
homepage = "https://gitlab.com/andybalaam/wysiwyg-rust"
repository = "https://gitlab.com/andybalaam/wysiwyg-rust"
description = "Swift and Kotlin bindings for wysiwyg-rust"
keywords = ["matrix", "chat", "messaging", "composer", "wysiwyg"]
license-file = { workspace = true }
name = "uniffi-wysiwyg-composer"
version = "2.38.1"
rust-version = { workspace = true }

[features]
default = []
assert-invariants = ["wysiwyg/assert-invariants"]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
# Keep the uniffi version here in sync with the installed version of
# uniffi-bindgen that is called from
# ../../examples/example-android/app/build.gradle
html-escape = "0.2.11"
matrix_mentions = { path = "../../crates/matrix_mentions" }
uniffi = { workspace = true }
uniffi_macros = { workspace = true }
widestring = "1.0.2"
wysiwyg = { path = "../../crates/wysiwyg" }

[build-dependencies]
uniffi_build = { workspace = true, features = ["builtin-bindgen"] }
