[package]
authors = ["Andy Balaam <andy.balaam@matrix.org>"]
edition = "2021"
homepage = "https://gitlab.com/andybalaam/wysiwyg-rust"
repository = "https://gitlab.com/andybalaam/wysiwyg-rust"
description = "Model code to power a rich text editor for Matrix"
keywords = ["matrix", "chat", "messaging", "composer", "wysiwyg"]
license-file = { workspace = true }
name = "wysiwyg"
version = "2.38.1"
rust-version = { workspace = true }

[features]
default = ["sys"]
js = ["dep:wasm-bindgen", "dep:web-sys"]
sys = ["dep:html5ever"]
assert-invariants = []

[dependencies]
cfg-if = "1.0.0"
html-escape = "0.2.11"
html5ever = { version = "0.27.0", optional = true }
once_cell = "1.13.0"
pulldown-cmark = { version = "0.11.0", default-features = false, features = ["html"] }
strum = "0.26"
strum_macros = "0.26"
unicode-segmentation = "1.7.1"
wasm-bindgen = { version = "0.2.83", default-features = false, optional = true }
web-sys = { version = "0.3.60", default-features = false, features = ["Document", "DomParser", "HtmlElement", "Node", "NodeList", "SupportedType"], optional = true }
widestring = "1.0.2"
indoc = "2.0"
url="2.3.1"
email_address="0.2.4"
regex="1.9.5"
matrix_mentions = { path = "../matrix_mentions" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
speculoos = "0.11.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.33"
