name: Wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('wasm-build-main-{0}', github.sha) || format('wasm-build-pr-{0}', github.ref)  }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rust
      run: |
        rustup set profile minimal
        rustup show # installs from rust-toolchain.toml
    - name: Install `wasm-pack`
      run: cargo install wasm-pack
    - name: Test the `wysiwyg` crate
      working-directory: crates/wysiwyg
      run: wasm-pack test --release --firefox --headless -- --no-default-features --features js
